### ISSUE TITLE
Missing cimgui library for macOS

### ISSUE THREAD

**Issue by peterdijkstra** [realgamessoftware/dear-imgui-unity-dev#1]
The upm package is missing the macOS library (.dylib) file for cimgui. Simply cloning the cimgui repo and building it from macOS seems to be working fine, although I'm not entirely sure where cimgui-freetype comes from.

I can make a pull request for the main cimgui library, let me know

**Comment by Arcnor** [comment]
`cimgui-freetype` seems to come from this own repository, you can see the source + cmake files there. I've also found this problem and I'd like to know if I should fix it myself or wait for a more "official" fix :).

**Comment by goncalo** [comment]
Sorry for the missing library. The reason for it is that I don't have access to a macOS environment at the time to build and test it. Pull requests would be welcomed.

If everything goes right the process should just be executing `build-native.sh`, dragging the resulting `cimgui` and `cimgui-freetype` libs from `src/build` into the `dear-imgui-project/Packages/dear-imgui-unity/Plugins` folder of the package and setting the proper platform settings for both.

**Comment by peterdijkstra** [comment]
Seems like the libraries are included now? :-)

Freetype rasterizer (I take it that's what cimgui-freetype is good for) also works
